let resumeData = {
    "imagebaseurl":"http://localhost:3000/",
    "name": "Vishal Kanabargi",
    "role": "FullStack Developer",
    "experience": "4",
    "deliveredProjectTechStack": "NodeJs, ReactJs, AWS, APIGEE and MuleSoft",
    "aboutMe": "I have over 4 years of experience as a Senior engineer. While I'm a proficient full-stack developer, my expertise is in building scalable backend services (API Developement and management, developer portal, stream processing, and async mechanisms).I love building things. While hard engineering problems are often intrinsically fun to tackle, I'm most attracted to solving real customer problems with a business justification. I'm looking for a senior individual contributor role where I can take on on collaborative team leadership responsibilites, and gain experience with architecture and project management.",
    "ContactInfo_Name": "Vishal Santosh Kanabargi",
    "App_Name": "Flat No: 202, Tirumla Residency",
    "Address": "12th Cross Rd, 3rd Phase, J.P Nagar, Bengaluru, Karnataka 560078",
    "Mobile_No": "8296864448",
    "Gmail": "tapaselectrical059@gmail.com",
    "responsibilites1": "• Well experienced as an API Development and API Gateway with good experience in implementation, integration, content management, Design and Documentation of APIs",
    "responsibilites2": "• Involving in architecture calls and collecting the requirement and taking ownership of building API gateway and Node.js API integrated API’s",
    "responsibilites3": "• Experienced in Continuous Development and Continuous Integration using maven, Jenkins and Bit Bucket.",
    "responsibilites4": "• Take ownership of software components and associated development and testing in terms of timelines and quality. (Agile Methodology).",
    "responsibilites5": "• Designing API’s on Confluence: API whiteboard Design, NB Spec, Mediation, Sandbox Design pages as well as on Swagger (Open API spec).",
    "responsibilites6": "• Utilized code repositories such as GitHub, BitBucket and Visual studio Team foundation servers to manage the code.",
    "responsibilites7": "• Integrated multiple third - party plugins/scripts/apis with the web application to inherit its features.",
    "responsibilites8": "• Detailed documentation all related work as per company's methodology and creating products and publishing it to the portal.",
    "responsibilites9": "• Given the series of trainings to new joiners to the team on different technologies.",
    "ArchitectureAndTechnologies":  ["API Development", "API Management", "Microservices", "Sereverless Functions", "Swagger", "REST Services", "SOAP Services", "Maven", "ELK stack", "Node.js", "Sonarqube", "Plant-UML", "ReactJs", "CSS3", "Linux"],
    "programmingLanguages": [ "JavaScript", "Core Java", "Spring Boot", "RAML", "Data Weave Expression Language", "YAML", "TypeScript", "HTML5" ],
    "nodeModules":  [ "Express", "Async", "JOI", "TsLint", "TypeScript", "Request", "Axios", "Mongoose", "Sinon", "Jest","Mocha chai", "Serverless", "Dotenv", "Webpack", "Mongodb-memory-server", "Sequelize etc.." ],
    "cloudTechnologies": [ "GCP Functions", "AWS Lambda", "IAM", "EC2", "S3 Bucket", "Code Build", "Route 53", "CloudFront", "CloudWatch" ],
    "APISecurities": [ "Oauth 2.0", "JWT token", "SSL", "Oauth Server", "CORS", "CSRF Token" ],
    "APIManagementTools": [ "APIGEE (API Management tool)", "MuleSoft (Integration Platform ESB)", "Zuul API Gateway" ],
    "testingTechnologies": [ "Cucumber", "Mocha-Chai", "JEST", "Postman" ],
    "codeRepositories": [ "SVN", "GitHub", "Bitbucket"],
    "database": [ "MongoDB", "Oracle 11g", "MySQL"],
    "ManagementTools": ["Confluence", "JIRA", "Bugzilla", "Maven", "Jenkins"],

    }
  export default resumeData